name: Dev Deploy

on:
    push:
        branches:
            - dev

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-assume-tole-arn: <arn>
            aws-region: <region>
            aws-bucket-statefile: "<bucket>"
