name: Dev Deploy

on:
    push:
        branches:
            - dev

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            # aws-assume-role-arn: "${secrets.AWS_ROLE_ARN}}"
            # aws-region: "${AWS_REGION}}"
            # aws-bucket-statefile: "${secrets.AWS_BUCKET}}"
            destroy: false
