name: Production Deploy

on:
    push:
        branches:
            - prod

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: prod
            aws-assume-tole-arn: "arn:aws:iam::719836617769:role/GitHub_Actions"
            aws-region: "us-east-2"
            aws-bucket-statefile: "s3.gregorian"
            destroy: destroy