name: Production Deploy

on:
    push:
        branches:
            - prod

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: prod
            aws-assume-tole-arn: "${{secrets.AWS_ROLE_ARN}}"
            aws-region: "${{secrets.AWS_REGION}}"
            aws-bucket-statefile: "${{secrets.AWS_BUCKET}}"
            destroy: false
