name: Production Deploy

on:
    push:
        branches:
            - prod

permissions:
    id-token: write
    contents: write

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: prod
            # aws-assume-tole-arn: "${{}}"
            # aws-region: "us-east-2"
            # aws-bucket-statefile: "${secrets.AWS_BUCKET}}"
            destroy: false
