

# services:
#   megasocial-app:
#     image: 719836617769.dkr.ecr.us-east-2.amazonaws.com/megasocial-app:latest
#     container_name: megasocial-app
#     restart: always
#     environment: 
#       - MYSQL_IP=127.0.0.1
#     ports: 
#       - 80:8080
#     network_mode: "host"
#     volumes:
#       - vol-megasocial:/megasocial

# volumes:
#   vol-megasocial: